name: CICD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9,3.7,3.8]
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: ${{  matrix.python-version }}

    - name: Install dependencies
      id: make_install
      run: |
        make install
    
    - name: Format code with black
      id: make_format
      run: |
        make format
    - name: Lint with ruff
      id: make_lint
      run: |
        make lint

    - name: Test with pytest
      id: make_test
      run: |
        make test
